import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';
const root=process.cwd(),compiled=JSON.parse(fs.readFileSync('qa/backend/compiled.json','utf8'));
const ORG='00000000-0000-4000-8000-000000000011',USER='00000000-0000-4000-8000-000000000012';
function harness(options={}){
 let handler,cache=new Map(),calls=[],sent=[],changes=[];
 const env={SUPABASE_URL:'https://qa.invalid',SUPABASE_ANON_KEY:'qa-public',SUPABASE_SERVICE_ROLE_KEY:'qa-server',WOMPI_CLIENT_ID:'qa-app',WOMPI_CLIENT_SECRET:'qa-secret-never-live',APP_PUBLIC_URL:'https://linkare.example.invalid',...options.env};
 const order={id:'order1',external_reference:'LINKARE-order1',plan_code:'semiannual',plan_name:'Profesional semestral',amount_cents:22000,months:6,currency:'USD',status:'creating',is_test:true};
 class Query{constructor(table){this.table=table;this.filters=[];}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}update(v){changes.push({table:this.table,...v});return this;}insert(v){changes.push({table:this.table,...v});return this;}async maybeSingle(){return {data:options.memberAbsent?null:{id:'member',role:options.role||'owner',active:options.active!==false,permissions:options.permissions||{}},error:null};}then(resolve,reject){return Promise.resolve({data:[],error:null}).then(resolve,reject);}}
 const db={auth:{getUser:async token=>({data:{user:token==='valid-token'?{id:USER,email:'doctor@example.invalid',email_confirmed_at:'2026-09-01'}:null},error:token==='valid-token'?null:{message:'invalid'}})},from:t=>new Query(t),rpc:async(name,args)=>{calls.push({name,args});if(name==='linkare_rate_v3')return {data:true,error:null};if(name==='linkare_reserve_order_v3')return {data:{existing:options.existing===true,order:options.existing?{...order,payment_url:'https://s.wompi.sv/existing',status:'pending',is_test:false}:order},error:null};if(name==='linkare_confirm_payment_v3')return {data:{ok:true},error:null};return {data:null,error:null};}};
 const fetch=async(url,init={})=>{sent.push({url,body:init.body?.toString()});if(url.includes('connect/token'))return new Response(JSON.stringify({access_token:'qa-oauth'}));if(url.endsWith('/Aplicativo'))return new Response(JSON.stringify({nombre:'QA',estaProductivo:true,numeroCuenta:'DO-NOT-EXPOSE'}));if(url.endsWith('/EnlacePago'))return new Response(JSON.stringify({idEnlace:'link1',urlEnlace:'https://s.wompi.sv/qa',estaProductivo:true}));throw Error('Unexpected outbound request');};
 const context=vm.createContext({Request,Response,Headers,URL,URLSearchParams,TextEncoder,TextDecoder,AbortSignal,console:{error:()=>{},log:()=>{}},crypto:crypto.webcrypto,fetch,Deno:{env:{get:k=>env[k]},serve:fn=>handler=fn},Date,setTimeout,clearTimeout,btoa});
 function load(file){file=path.posix.normalize(file);if(cache.has(file))return cache.get(file).exports;const entry=compiled.modules[file];assert.ok(entry,'Missing compiled fixture '+file);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),entry.sha256,'Rebuild backend QA fixture after editing '+file);const module={exports:{}};cache.set(file,module);const fn=vm.runInContext(`(function(require,module,exports){${entry.javascript}\n})`,context);fn(p=>p.startsWith('https://esm.sh/@supabase/')?{createClient:()=>db}:load(path.posix.join(path.posix.dirname(file),p)),module,module.exports);return module.exports;}
 return {load,calls,sent,changes,env,request:async (name,input={},token='valid-token')=>{load(`supabase/functions/${name}/index.ts`);return handler(new Request('https://qa.invalid/function',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(input)}));},raw:async(name,raw,hash)=>{load(`supabase/functions/${name}/index.ts`);return handler(new Request('https://qa.invalid/function',{method:'POST',headers:{'wompi_hash':hash||''},body:raw}));}};
}
test('payment endpoint rejects requests without a real bearer token',async()=>{const h=harness(),r=await h.request('wompi-create-link',{organizationId:ORG,planCode:'annual'},null);assert.equal(r.status,401);assert.equal(h.sent.length,0);});
test('secretary cannot generate a payment even with extra fake permissions',async()=>{const h=harness({role:'secretary',permissions:{doctor:true,settingsManage:true}}),r=await h.request('wompi-create-link',{organizationId:ORG,planCode:'monthly'});assert.equal(r.status,403);assert.equal(h.sent.length,0);});
test('inactive membership is refused before talking to Wompi',async()=>{const h=harness({active:false}),r=await h.request('wompi-app-info',{organizationId:ORG});assert.equal(r.status,403);});
test('checkout ignores client amount and uses server order snapshot',async()=>{const h=harness(),r=await h.request('wompi-create-link',{organizationId:ORG,planCode:'semiannual',amount:0.01,months:999});assert.equal(r.status,200);const payment=JSON.parse(h.sent.find(c=>c.url.endsWith('/EnlacePago')).body);assert.equal(payment.monto,220);assert.equal(payment.configuracion.esMontoEditable,false);assert.equal(payment.configuracion.esCantidadEditable,false);assert.equal(payment.identificadorEnlaceComercio,'LINKARE-order1');assert.equal(h.changes.at(-1).status,'pending');});
test('existing checkout returns its URL without creating another link',async()=>{const h=harness({existing:true}),r=await h.request('wompi-create-link',{organizationId:ORG,planCode:'semiannual'});assert.equal(r.status,200);assert.equal(h.sent.filter(c=>c.url.endsWith('/EnlacePago')).length,0);});
test('Wompi app status never returns a bank account',async()=>{const h=harness(),r=await h.request('wompi-app-info',{organizationId:ORG});assert.equal(r.status,200);const text=await r.text();assert.ok(!text.includes('DO-NOT-EXPOSE'));assert.ok(!text.includes('qa-secret'));});
const event=()=>({Aplicativo:{Id:'qa-app'},ResultadoTransaccion:'ExitosaAprobada',EsProductiva:true,EnlacePago:{IdentificadorEnlaceComercio:'LINKARE-order1'},Monto:220,FechaTransaccion:'2026-09-08T12:00:00Z',IdTransaccion:'transaction-qa-only'});
const sign=raw=>crypto.createHmac('sha256','qa-secret-never-live').update(raw).digest('hex');
test('webhook rejects a missing or forged HMAC',async()=>{for(const hash of ['', '0'.repeat(64)]){const h=harness(),r=await h.raw('wompi-webhook',JSON.stringify(event()),hash);assert.equal(r.status,401);assert.equal(h.calls.length,0);}});
test('webhook rejects an event for another application despite valid HMAC',async()=>{const h=harness(),raw=JSON.stringify({...event(),Aplicativo:{Id:'other-app'}}),r=await h.raw('wompi-webhook',raw,sign(raw));assert.equal(r.status,400);assert.equal(h.calls.length,0);});
test('nonproductive event does not activate a real subscription',async()=>{const h=harness(),raw=JSON.stringify({...event(),EsProductiva:false}),r=await h.raw('wompi-webhook',raw,sign(raw));assert.equal(r.status,400);assert.equal(h.calls.length,0);});
test('verified webhook passes exact cents and reference to database validator',async()=>{const h=harness(),raw=JSON.stringify(event()),r=await h.raw('wompi-webhook',raw,sign(raw));assert.equal(r.status,200);assert.equal(h.calls[0].name,'linkare_confirm_payment_v3');assert.equal(h.calls[0].args.amount,22000);assert.equal(h.calls[0].args.ref,'LINKARE-order1');});
test('secretary cannot invite another user by calling the team API',async()=>{const h=harness({role:'secretary'}),r=await h.request('linkare-team',{organizationId:ORG,action:'invite',email:'other@example.invalid',name:'Other'});assert.equal(r.status,403);assert.equal(h.changes.length,0);});
