import test from 'node:test';import assert from 'node:assert/strict';
import {createEmptyData,normalizeData} from '../../src/data.js';
import {hasPermission,getActiveUser} from '../../src/practice.js';
import {PLAN_OPTIONS,addCalendarMonths,subscriptionView} from '../../src/domain/plans.js';
import {upsertEncounter} from '../../src/v2features.js';
test('new clinic initializes without sample users, patients or payments',()=>{const data=createEmptyData();for(const key of ['users','patients','appointments','payments','alerts'])assert.equal(data[key].length,0);assert.equal(getActiveUser(data),null);assert.equal(hasPermission(data,'clinicalView'),false);});
test('secretary clinical override is not accepted by the UI permission helper',()=>{const data=normalizeData({users:[{id:'s',role:'secretary',active:true,permissions:{clinicalView:true,patientsView:true}}],settings:{activeUserId:'s'}});assert.ok(hasPermission(data,'patientsView'));assert.equal(hasPermission(data,'clinicalView'),false);assert.equal(hasPermission(data,'usersManage'),false);});
test('missing user id does not fall back to doctor privileges',()=>{const data=normalizeData({users:[{id:'d',role:'doctor'}],settings:{activeUserId:'missing'}});assert.equal(getActiveUser(data),null);assert.equal(hasPermission(data,'clinicalView'),false);});
test('commercial display catalog contains only the three requested modalities',()=>assert.deepEqual(PLAN_OPTIONS.map(p=>[p.code,p.amount,p.months]),[['monthly',40,1],['semiannual',220,6],['annual',400,12]]));
test('monthly renewal clamps at the end of short months',()=>{assert.equal(addCalendarMonths('2026-01-31T12:00:00Z',1),'2026-02-28T12:00:00.000Z');assert.equal(addCalendarMonths('2024-01-31T12:00:00Z',1),'2024-02-29T12:00:00.000Z');});
test('annual leap-day renewal is one calendar year, not 365 days',()=>assert.equal(addCalendarMonths('2024-02-29T12:00:00Z',12),'2025-02-28T12:00:00.000Z'));
test('period display separates no subscription, active, grace and expired',()=>{const now=new Date('2026-09-09T12:00:00Z');assert.equal(subscriptionView(null,now).active,false);assert.equal(subscriptionView({current_period_end:'2026-10-20T12:00:00Z'},now).label,'Activo');assert.equal(subscriptionView({current_period_end:'2026-09-08T12:00:00Z'},now).label,'Periodo de gracia');assert.equal(subscriptionView({current_period_end:'2026-09-01T12:00:00Z'},now).label,'Vencido');});
test('finalizing a note records the authenticated author',()=>{const data=normalizeData({patients:[{id:'p',name:'Name',consultations:[]}],appointments:[]});const result=upsertEncounter(data,'p',{id:'n',startedAt:new Date().toISOString(),freeNotes:'Clinical note'},{finalize:true,user:{id:'real-auth-id'}});assert.equal(result.encounter.signedBy,'real-auth-id');assert.ok(result.encounter.signedAt);assert.equal(result.encounter.status,'completed');});

test('reload preserves signed note bytes and extra signature metadata',()=>{const note={id:'n',status:'signed',freeNotes:'  exact note\n',signedAt:'2026-09-01T12:00:00Z',signedBy:'u',signatureVersion:1};const d=normalizeData({patients:[{id:'p',name:'Patient',consultations:[note]}]});assert.deepEqual(d.patients[0].consultations[0],note);});
test('archived document does not become active on reload',()=>{const d=normalizeData({patients:[{id:'p',name:'Patient',documents:[{id:'doc',name:'Letter.pdf',archived:true,archivedAt:'2026-09-01'}]}]});assert.equal(d.patients[0].documents[0].archived,true);});
test('legacy medication hydration does not invent server-owned identity',()=>{const d=normalizeData({patients:[{id:'p',name:'Patient',lastVisit:'2026-08-01',medications:[{id:'legacy-med',name:'Legacy',dose:'10 mg',startDate:'2026-07-01'}]}]});assert.equal(d.patients[0].medications[0].createdAt,null);});
