import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildPrescriptionPrintHtml,prescriptionItemFromMedication,savePrescription,voidPrescription} from '../../src/practice.js';
const old={id:'rx-1',number:'RX-2026-0001',date:'2026-09-21T12:00:00.000Z',createdAt:'2026-09-20T00:00:00.000Z',createdBy:'doctor',doctorName:'Doctor QA',status:'active',observations:'INTERNAL SECRET',generalInstructions:'Tomar con agua',items:[{id:'i',medication:'Synthetic medication',directions:'Original text'}]};
const data=role=>({organization:{name:'QA',clinician:'Doctor QA',professionalLicense:'JVPM 123'},settings:{activeUserId:role},users:[{id:role,role,active:true,permissions:{patientsView:true,prescriptionsEdit:true}}],patients:[{id:'p',name:'Synthetic',age:40,diagnosis:'QA',prescriptions:[old]}]});
for(const role of ['doctor','secretary'])test(role+' can correct an existing prescription without creating a duplicate',()=>{
 const d=data(role);const r=savePrescription(d,'p',{...old,date:'2026-09-21',items:[{...old.items[0],directions:'Corrected text'}]});assert.equal(r.data.patients[0].prescriptions.length,1);assert.equal(r.prescription.id,old.id);assert.equal(r.prescription.number,old.number);assert.equal(r.prescription.createdBy,old.createdBy);assert.equal(r.prescription.updatedBy,role);assert.equal(r.prescription.items[0].directions,'Corrected text');assert.equal(d.patients[0].prescriptions[0].items[0].directions,'Original text');
});
test('secretary correction capability does not allow issuing a new prescription',()=>{assert.throws(()=>savePrescription(data('secretary'),'p',{date:'2026-09-21',items:old.items}),/permiso/);});
for(const role of ['doctor','secretary'])test(role+' can void a prescription without removing its record',()=>{
 const d=data(role);const r=voidPrescription(d,'p',old.id,'Error de transcripción');assert.equal(r.data.patients[0].prescriptions.length,1);assert.ok(r.prescription.voidedAt);assert.equal(r.prescription.voidedBy,role);assert.equal(r.prescription.status,'voided');assert.equal(r.prescription.voidReason,'Error de transcripción');assert.equal(d.patients[0].prescriptions[0].voidedAt,undefined);assert.throws(()=>savePrescription(r.data,'p',{...r.prescription,date:'2026-09-21'}),/anulada/);
});
test('voided prescription print is marked and excludes internal observations',()=>{const d=data('doctor');const rx=voidPrescription(d,'p',old.id,'Error de dosis').prescription;const output=buildPrescriptionPrintHtml(d,d.patients[0],rx);assert.match(output,/RECETA ANULADA/);assert.match(output,/Error de dosis/);assert.match(output,/Firma y sello/);assert.doesNotMatch(output,/INTERNAL SECRET/);assert.match(output,/Tomar con agua/);});
test('prescription item keeps an immutable medication snapshot',()=>{const medication={id:'med-1',name:'Original',dose:'10 mg',frequency:'cada mañana',clinicalNotes:'nota'};const item=prescriptionItemFromMedication(medication);medication.name='Changed';medication.dose='20 mg';assert.equal(item.medication,'Original');assert.equal(item.strength,'10 mg');assert.equal(item.sourceMedicationId,'med-1');});
