import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';
import {permissionAllowed,PERMISSION_KEYS} from '../../src/domain/permissions.js';
const compiled=JSON.parse(fs.readFileSync('qa/backend/compiled.json','utf8'));
const ORG='00000000-0000-4000-8000-000000000011',USER='00000000-0000-4000-8000-000000000012';
function harness(options={}){
 let handler;const changes=[],cache=new Map();
 class Query{constructor(table){this.table=table;this.filters={};}select(){return this;}eq(k,v){this.filters[k]=v;return this;}insert(row){this.row=row;changes.push({table:this.table,...row});return this;}update(row){changes.push({table:this.table,...row});return this;}
 async single(){return {data:{id:'invite-id',...this.row},error:null};}
 async maybeSingle(){return {data:this.table==='linkare_invites_v3'?options.invite||null:this.filters.user_id===USER?{role:options.role||'owner',active:options.active!==false,permissions:options.permissions||{}}:{id:'target',role:options.targetRole||'clinical_assistant',active:true},error:null};}
 then(resolve,reject){const data=this.table==='organization_members'?['owner','psychiatrist','clinical_assistant','secretary'].map((role,i)=>({user_id:'user'+i,role,active:true})):[];return Promise.resolve({data,error:null}).then(resolve,reject);}}
 const db={from:t=>new Query(t),rpc:async()=>({data:true,error:null}),auth:{getUser:async()=>({data:{user:{id:USER,email:'owner@example.invalid',email_confirmed_at:'2026-09-01'}},error:null}),admin:{getUserById:async()=>({data:{user:{email:'qa@example.invalid'}}}),inviteUserByEmail:async()=>({error:null})}}};
 const env={SUPABASE_URL:'https://qa.invalid',SUPABASE_SERVICE_ROLE_KEY:'qa-server',SUPABASE_ANON_KEY:'qa-public',APP_PUBLIC_URL:'https://nexamind-clinical.vercel.app',CORS_ORIGINS:'https://nexamind-clinical-git-main-clinqui7s-projects.vercel.app'};
 const context=vm.createContext({Request,Response,Headers,URL,console:{error(){}},crypto:crypto.webcrypto,Date,Deno:{env:{get:k=>env[k]},serve:f=>handler=f}});
 const load=file=>{file=path.posix.normalize(file);if(cache.has(file))return cache.get(file).exports;const entry=compiled.modules[file];assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),entry.sha256);const module={exports:{}};cache.set(file,module);vm.runInContext(`(function(require,module,exports){${entry.javascript}\n})`,context)(p=>p.startsWith('https://esm.sh/')?{createClient:()=>db}:load(path.posix.join(path.posix.dirname(file),p)),module,module.exports);return module.exports;};
 return {changes,load,async request(body={},method='POST',origin){load('supabase/functions/linkare-team/index.ts');return handler(new Request('https://qa.invalid',{method,headers:{Authorization:'Bearer qa-token','Content-Type':'application/json',...(origin?{Origin:origin}:{})},...(method==='POST'?{body:JSON.stringify({organizationId:ORG,...body})}:{})}));}};
}
for(const role of ['psychiatrist','clinical_assistant','secretary'])test('team API denies privileged actions from '+role,async()=>{for(const action of ['list','invite','update','toggle','revoke','resend']){const h=harness({role,permissions:{usersManage:true,settingsManage:true}});assert.equal((await h.request({action})).status,403);assert.equal(h.changes.length,0);}});
for(const [role,expected] of [['doctor','psychiatrist'],['nurse','clinical_assistant'],['secretary','secretary']])test('team invites '+role+' with server-owned role and sanitized permissions',async()=>{const h=harness();const r=await h.request({action:'invite',role,name:'New member',email:'new@example.invalid',title:'Title',phone:'123',permissions:{patientsView:true,clinicalView:true,root:true,usersManage:true}});assert.equal(r.status,200);const inv=h.changes.find(x=>x.table==='linkare_invites_v3');assert.equal(inv.requested_role,expected);assert.equal(inv.permissions.root,undefined);assert.equal(inv.permissions.usersManage,false);assert.equal(inv.permissions.clinicalView,role!=='secretary');assert.equal(inv.phone,'123');});
test('team rejects inviting owner and modifying an existing owner',async()=>{assert.equal((await harness().request({action:'invite',role:'owner',name:'New',email:'new@example.invalid'})).status,400);assert.equal((await harness({targetRole:'owner'}).request({action:'update',userId:'other',role:'doctor'})).status,403);});
test('team returns distinct owner, doctor, nurse and secretary roles',async()=>{const result=await (await harness().request({action:'list'})).json();assert.deepEqual(result.users.map(u=>u.role),['owner','doctor','nurse','secretary']);});
test('owner can update nurse permissions and toggle membership',async()=>{const h=harness();assert.equal((await h.request({action:'update',userId:'other',role:'nurse',name:'Nurse',permissions:{patientsView:true,clinicalView:true,clinicalEdit:false}})).status,200);assert.equal(h.changes[0].permissions.clinicalEdit,false);assert.equal((await h.request({action:'toggle',userId:'other'})).status,200);assert.equal(h.changes.find(x=>x.active===false).table,'organization_members');});
test('CORS OPTIONS allows configured origins and rejects foreign origins',async()=>{for(const origin of ['https://nexamind-clinical.vercel.app','https://nexamind-clinical-git-main-clinqui7s-projects.vercel.app','http://localhost:4173','http://127.0.0.1:4173']){const r=await harness().request({},'OPTIONS',origin);assert.equal(r.status,200);assert.equal(r.headers.get('access-control-allow-origin'),origin);}assert.equal((await harness().request({},'OPTIONS','https://untrusted.invalid')).headers.get('access-control-allow-origin'),null);});
test('shared auth retains every hotfix export and publicKey helper',()=>{const auth=harness().load('supabase/functions/_shared/auth.ts');for(const k of ['publicKey','requireUser','requireMember','limitAction','safeApiMessage'])assert.equal(typeof auth[k],'function');assert.equal(auth.publicKey(),'qa-public');});
test('frontend and Edge permission decisions agree for every role and permission',()=>{const edge=harness().load('supabase/functions/_shared/permissions.ts');for(const role of ['owner','doctor','psychiatrist','nurse','clinical_assistant','secretary','read_only'])for(const permissions of [{},Object.fromEntries(PERMISSION_KEYS.map(k=>[k,true])),{clinicalEdit:true,clinicalView:true,patientsView:false}])for(const key of [...PERMISSION_KEYS,'unknown'])assert.equal(edge.permissionAllowed({role,active:true,permissions},key),permissionAllowed({role,active:true,permissions},key),role+':'+key);});
