import {createServer} from 'vite';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=process.env.LINKARE_QA_ROOT||fileURLToPath(new URL('../../',import.meta.url));
const db=new PGlite({extensions:{pgcrypto}});
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert on storage.objects to authenticated;`);
for(const p of ['supabase/00_BASE.sql','supabase/migrations/202609080001_linkare_v3.sql','supabase/migrations/20260921163356_enable_free_access.sql','supabase/migrations/20260921170106_free_access_and_team_permissions.sql','supabase/migrations/20260921170933_secretary_prescription_corrections.sql','supabase/migrations/20260921182203_archive_prescriptions.sql','supabase/migrations/20260921201729_operational_clinical_lifecycles.sql','supabase/migrations/20260921210315_daily_agenda_and_automation.sql','supabase/migrations/20260921211201_document_templates.sql','supabase/migrations/20260921213000_scoped_calendars_and_family_reminders.sql','supabase/migrations/20260921214500_legacy_migration_staging.sql','supabase/migrations/20260921223000_archive_medications.sql','supabase/migrations/20260921232000_fix_medication_identity_and_archive.sql'])await db.exec(fs.readFileSync(root+'/'+p,'utf8'));
await db.exec(`insert into auth.users values('10000000-0000-4000-8000-000000000001','owner@example.invalid',now(),'{"clinic_name":"QA Isolated","full_name":"QA Owner"}'),('10000000-0000-4000-8000-000000000002','other@example.invalid',now(),'{"clinic_name":"QA Other","full_name":"QA Other"}');`);
await db.exec(`select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',false);select public.linkare_bootstrap_v3(null);`);
for(const [name,role,id] of [['doctor','psychiatrist',3],['nurse','clinical_assistant',4],['secretary','secretary',5]]){
 const uid='10000000-0000-4000-8000-00000000000'+id;
 await db.query('insert into auth.users values($1,$2,now(),$3)',[uid,name+'@example.invalid','{}']);
 await db.query("insert into public.organization_members(organization_id,user_id,role,display_name,active,permissions) select organization_id,$1,$2,$3,true,$4 from public.organization_members where user_id='10000000-0000-4000-8000-000000000001'",[uid,role,name,JSON.stringify({patientsView:true,patientsCreate:true,patientsEdit:true,appointmentsManage:true,remindersManage:true,clinicalView:name==='doctor',prescriptionsEdit:name!=='nurse',documentsView:name==='nurse',documentsManage:name==='nurse'})]);
}
let queue=Promise.resolve();let delay=0;let fail=false;
const server=await createServer({root,configFile:false,define:{'import.meta.env.VITE_SUPABASE_URL':'"https://qa.invalid"','import.meta.env.VITE_SUPABASE_ANON_KEY':'"qa-public-key"'},resolve:{alias:{'@supabase/supabase-js':fileURLToPath(new URL('./qa-sdk.js',import.meta.url))}},server:{host:'127.0.0.1',port:4173,fs:{allow:[root,fileURLToPath(new URL('.',import.meta.url))]}},plugins:[{name:'isolated-qa-db',configureServer(server){server.middlewares.use('/__qa',(req,res)=>{let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{queue=queue.then(async()=>{try{const x=JSON.parse(body);if(x.control){delay=x.delay||0;fail=!!x.fail;res.end(JSON.stringify({ok:true}));return;}
await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[x.user||'']);await db.exec('set role authenticated');let data;
if(x.name){if(x.name==='linkare_save_changes_v3'){if(delay)await new Promise(r=>setTimeout(r,delay));if(fail)throw new Error('QA_CONNECTION_FAILED');}
const args=x.args||{};const allow={linkare_access_v3:['org'],linkare_bootstrap_v3:['requested_name'],linkare_load_state_v3:['org'],linkare_save_changes_v3:['org','changes'],linkare_archive_medication_v1:['p_org','p_patient_id','p_medication_id','p_reason']};const keys=allow[x.name];if(!keys)throw Error('Unknown RPC');data=(await db.query('select public.'+x.name+'('+keys.map((_,i)=>'$'+(i+1)).join(',')+') data',keys.map(k=>typeof args[k]==='object'&&args[k]!==null?JSON.stringify(args[k]):args[k]??null))).rows[0].data;
}else if(x.storage){await db.query("insert into storage.objects(bucket_id,name) values('patient-documents',$1)",[x.path]);data={path:x.path};
}else if(x.table==='patient_document_audit'&&x.insert){const d=x.insert;await db.query('insert into public.patient_document_audit(organization_id,patient_id,document_id,action,storage_path,actor_id,metadata) values($1,$2,$3,$4,$5,$6,$7)',[d.organization_id,d.patient_id,d.document_id,d.action,d.storage_path,d.actor_id,JSON.stringify(d.metadata)]);data={};
}else if(x.team){const boot=(await db.query('select public.linkare_bootstrap_v3(null) id')).rows[0].id;const loaded=(await db.query('select public.linkare_load_state_v3($1) data',[boot])).rows[0].data;data={ok:true,users:loaded.payload.users,invitations:[]};
}else if(['linkare_plans_v3','linkare_orders_v3','linkare_subscriptions_v3'].includes(x.table)){const rows=(await db.query('select * from public.'+x.table)).rows;data=x.single?rows[0]||null:rows;}else throw Error('Unknown table');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data,error:null}));
}catch(e){res.end(JSON.stringify({data:null,error:{message:e.message,code:e.code}}));}});});});}}]});
await server.listen();console.log('QA_SERVER_READY http://127.0.0.1:4173 isolated PostgreSQL, no production writes');

